server:
  port: 8081

spring:
  application:
    name: DataGeneratorService
  config:
    import: optional:file:.env[.properties]
  kafka:
    producer:
      bootstrap-servers: kafka-1:9092,kafka-2:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 10
      properties:
        retry:
          backoff:
            ms: 1000
        delivery:
          timeout:
            ms: 60000
        linger:
          ms: 0
        request:
          timeout:
            ms: 30000
        enable:
          idempotence: true
        max:
          in:
            flight:
              requests:
                per:
                  connection: 5